server:
  port: 8085
itemImgLocation: D:/kyo/pro
uploadPaths: file:///D://kyo//pro
spring:
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 100MB
      max-file-size: 20MB
  profiles:
    active: local
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
    hidden-method:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tsherpa
    username: root
    password: 1234
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.chunjae.pro05.entity
  mapper-locations: mappers/**/*.xml
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework: info

